### ISSUE TITLE
博客主域名无法访问

### ISSUE THREAD

**Issue by DargonXuan** [lbr77/lbr77#6]
stevelbr.top
stevelbr.ga
都无法访问了呢（~

**Comment by DargonXuan** [comment]
https://blog.stevelbr.top/ 可以
建议做一个转跳或者更新一下个人信息

**Comment by lbr77** [comment]
确实（之前不留神把主页删了然后一直都没有更新回来

谢谢大佬提醒！

**Comment by lbr77** [comment]
> https://blog.stevelbr.top/ 可以 建议做一个转跳或者更新一下个人信息

好吧我发现是因为根域名MX和CNAME的问题，已更新主页链接

**Comment by lbr77** [comment]
（然鹅并没有修好
垃圾Cloudflare

**Comment by lbr77** [comment]
Fixed
